### PR TITLE
Support filtering parameters for chaos events

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <yb532204897@gmail.com>

Update based on PR https://github.com/pingcap/chaos-mesh/pull/672.

@zhouqiang-cl I think we can do a release after this pr merged. Then users can try it much easier

### CODE REVIEW

**Comment by cwen0** [comment]
> @zhouqiang-cl I think we can do a release after this pr merged. Then users can try it much easier

We can release with chaos mesh synchronously

**Comment by cwen0** [comment]
In addition, we also need a document to describe how to use it.

**Comment by yeya24** [comment]
@cwen0  When is the next release of Chaos Mesh?

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
> @cwen0 When is the next release of Chaos Mesh?

This month.

**Comment by yeya24** [comment]
Not done. Needs more testing

**Comment by zhouqiang-cl** [comment]
Do we need to merge this pr after https://github.com/pingcap/chaos-mesh/pull/672

**Comment by yeya24** [comment]
@zhouqiang-cl  Seems still some bugs related to timestamps in this pr.

**Comment by zhouqiang-cl** [comment]
> @zhouqiang-cl Seems still some bugs related to timestamps in this pr.

got

**Comment by yeya24** [comment]
@zhouqiang-cl  @cwen0 This should be okay and good to merge. Please take a look and test, if everything is okay then this pr is good to go!

**Pull request merged**
